sudo: required

language:bash

services:
    - docker

before_install:
    - docker pull multiarch/ubuntu-core
    - docker pull multiarch/qemu-user-static
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
    - make TARGET=armhf
    - make TARGET=amd64
    - docker push meyskens/multiarch-nodejs
